const SRC_IP_DIMENSION = 'SRC IP Address';
const DEST_IP_DIMENSION = 'DEST IP Address';

module.exports = {
  SRC_IP_DIMENSION,
  DEST_IP_DIMENSION,
  PIVOT_DIMENSIONS: [SRC_IP_DIMENSION, DEST_IP_DIMENSION],
};
